// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// numericSquare
int numericSquare(int num);
RcppExport SEXP _viewscape_numericSquare(SEXP numSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type num(numSEXP);
    rcpp_result_gen = Rcpp::wrap(numericSquare(num));
    return rcpp_result_gen;
END_RCPP
}
// visibleLabel
NumericMatrix visibleLabel(const NumericVector viewpoint, const NumericMatrix dsm, const int pointNumber, const int resolution);
RcppExport SEXP _viewscape_visibleLabel(SEXP viewpointSEXP, SEXP dsmSEXP, SEXP pointNumberSEXP, SEXP resolutionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector >::type viewpoint(viewpointSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type dsm(dsmSEXP);
    Rcpp::traits::input_parameter< const int >::type pointNumber(pointNumberSEXP);
    Rcpp::traits::input_parameter< const int >::type resolution(resolutionSEXP);
    rcpp_result_gen = Rcpp::wrap(visibleLabel(viewpoint, dsm, pointNumber, resolution));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_viewscape_numericSquare", (DL_FUNC) &_viewscape_numericSquare, 1},
    {"_viewscape_visibleLabel", (DL_FUNC) &_viewscape_visibleLabel, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_viewscape(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
