# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

numericSquare <- function(num) {
    .Call('_viewscape_numericSquare', PACKAGE = 'viewscape', num)
}

visibleLabel <- function(viewpoint, dsm, pointNumber, resolution) {
    .Call('_viewscape_visibleLabel', PACKAGE = 'viewscape', viewpoint, dsm, pointNumber, resolution)
}

