# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cosAB <- function(xyp, zp, xyt, zt, xyn, zn) {
    .Call('_viewscape_cosAB', PACKAGE = 'viewscape', xyp, zp, xyt, zt, xyn, zn)
}

get_depths <- function(px, py, x, y, num) {
    .Call('_viewscape_get_depths', PACKAGE = 'viewscape', px, py, x, y, num)
}

multiLabel <- function(vpts, dsm, max_dis, vpth, h) {
    .Call('_viewscape_multiLabel', PACKAGE = 'viewscape', vpts, dsm, max_dis, vpth, h)
}

sectorValue <- function(k, b, x) {
    .Call('_viewscape_sectorValue', PACKAGE = 'viewscape', k, b, x)
}

visibleLabel <- function(viewpoint, dsm, h, max_dis) {
    .Call('_viewscape_visibleLabel', PACKAGE = 'viewscape', viewpoint, dsm, h, max_dis)
}

