#' sector_mask
#' @description The sector_mask function is designed to subset a viewshed based on
#' its viewpoint and the field of view
#'
#' @param viewshed viewshed object, generated by compute_viewshed()
#' @param fov Vector, specifying the field of view with two angles in degree (e.g. c(10,100))
#' for masking a viewshed based on its viewpoints.
#' See details.
#'
#' @details For defining the field of view ('fov'), angles range from 0 to 360 degrees,
#' with 0 inclusive and 360 exclusive. The initial angle must be smaller than the terminal
#' angle in the sequence c(a,b) (a < b). To capture the northeast quadrant of a viewshed,
#' one would use c(0,90), while the eastern quadrant would be delineated by c(45,315) as
#' shown below:
#' \tabular{rrr}{
#' 135 \tab 90 \tab 45 \cr
#' 180 \tab v \tab 0 \cr
#' 225 \tab 270 \tab 315 \cr
#' }
#' Here, 'v' represents the viewpoint, with angles measured clockwise from due north.
#'
#'
#' @return viewshed object
#' @seealso [compute_viewshed()]
#' @export
#'

sector_mask <- function(viewshed, fov) {
  viewshed@visible <- sectorMask(viewshed@visible,
                                 viewshed@viewpos,
                                 fov)
  return(viewshed)
}
