#' @import Rcpp

.onLoad <- function(libname, pkgname) {
  Rcpp::sourceCpp(system.file("extdata/visibleLabel.cpp", package ="viewscape"),
                  env = asNamespace("viewscape"))
  cat("VIEWSCAPE_2.0\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/MMM/MMM/M///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/M////MM/M/MM//////MM//MM///MM///MMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/M////MM//MM/MM/MMMM//MMM///MM///MM/////MM//MM/MMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMM/////MM/MM/M/MMM/mn=======nmMMMM/M/MM/////MMM///MMM/MMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMM////MM/MMMMMMmn-=====nMMMMMMMMMMn=====nmMMMMMM///MMM//MMM////M/MMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMM///M/MMMMmm-=====nmMMMMm::::...::::NMMMn-=======nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMM//MMMMMMm-====nMMMN:.                 ..:::::MMMMn-======nmMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMM///MMMM-===nMMN:::..      ////XXXooo        ...::::::::NMMn-====nmMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMM-==MMn:::..         ////XX??-||-oo             ...:::::::::NMM-===MMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMM-===MNn:..            ///XXXX??------oo             ..........::::MMM==MMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMM==:...              iiii'''ii??----oooo           ........::::MMM-===MMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMM==:.              iii'''''iiiii////oooo        ........:::MMMM-===MMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMM==:..           iii''''''iii///oooo       .......:::::MMM-===MMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMM==::.          iii'''''ooo//ooooo      ...::::::MMMM-==MMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMM==::..       iioo'''''//ooooo   ..::::::MMMM-==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMM==:::......ioooooooooo....:::::MMMMMM==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("M::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M\n")
  cat("M::██:::::::::██::██::██████::██::::██::::██::████████::███████:::::███::::::::█████████:::██████::M\n")
  cat("M:::██:::::::██::██::██::::::██:::████:::██::██::::::::██:::::██:::██:██::::::██::::::██::██:::::::M\n")
  cat("M::::██:::::██::██::██::::::██::██::██::██::████████::██::::::::::██::██:::::██::::::██::██::::::::M\n")
  cat("M:::::██:::██::██::██████::██:██::::██:██:::::::::██::██:::::::::███████::::█████████::███████:::::M\n")
  cat("M::::::██:██::██::██::::::███:::::::███:::██::::███::██:::::██::██::::██:::██:::::::::██:::::::::::M\n")
  cat("M:::::::███::██::██████::██:::::::::██:::█████████:::████████::██:::::██::██:::::::::███████:::::::M\n")
  cat("M::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::M\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  invisible()
}

.onUnload <- function(libpath)
{
  library.dynam.unload("viewscape", libpath)
}

#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/MMM/MMM/M///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMM/M////MM/M/MM//////MM//MM///MM///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMM/M////MM//MM/MM/MMMM//MMM///MM///MM/////MM//MM/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMM/////MM/MM/M/MMM/mn=======nmMMMM/M/MM/////MMM///MMM/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMM////MM/MMMMMMmn-=====nMMMMMMMMMMn=====nmMMMMMM///MMM//MMM////M/MMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMM///M/MMMMmm-======nMMMMm:::::::::::NMMMn-=======nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMM//MMMMMMm-====nMMMN::::::..............::::::MMMMn-======nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MM///MMMM-===nMMN:::::::....////XXXooo...........::::::::NMMn-====nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMM-==MMn:::...........////XX??-||-oo................:::::::::NMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMM
#MM-===MNn:..............///XXXX??------oo.......................::::MMM==MMMMMMMMMMMMMMMMMMMMMMMMMM
#MMM==:.................iiii'''ii??----oooo...................::::MMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMM==:...............iii'''''iiiii////oooo................:::MMMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMM==:::............iii''''''iii///oooo..............:::::MMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMM==::::.........iii'''''ooo//ooooo.........::::::MMMM-==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMM==::::::.....iioo'''''//ooooo.....::::::MMMM-==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMM==:::::::..ioooooooooo:::::::::MMMMMM==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MM..MMMMMMMMM..MM..MM......MM..MMMM..MMMM..MM.......MMM.......MMMMM...MMMMM.........MMMM......MMMMM
#MMM..MMMMMMM..MM..MM..MMMMMM..MM..M..MMM..MM..MMMMMMMM..MMMMM..MMM..M..MMMM..MMMMMM..MM..MMMMMMMMMM
#MMMM..MMMMM..MM..MM..MMMMMM..MM..MM..MM..MM........MM..MMMMMMMMMM..MM..MMM..MMMMMM..MM..MMMMMMMMMMM
#MMMMM..MMM..MM..MM......MM..M..MMMM..M..MMMMMMMMM..MM..MMMMMMMMM.......MMM.........MM.......MMMMMMM
#MMMMMM..M..MM..MM..MMMMMM...MMMMMMM...MMM..MMMM...MM...MMMM..MM..MMMM..MMM..MMMMMMMM..MMMMMMMMMMMMM
#MMMMMMM...MM..MM......MM..MMMMMMMMM..MMM.........MMM........MM..MMMMM..MM..MMMMMMMM.......MMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

