#' @import Rcpp

.onLoad <- function(libname, pkgname) {
  Rcpp::sourceCpp(system.file("extdata/visibleLabel.cpp", package ="viewscape"),
                  env = asNamespace("viewscape"))
  cat("loading... \n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/MMM/MMM/M///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/M////MM/M/MM//////MM//MM///MM///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMM/M////MM//MM/MM/MMMM//MMM///MM///MM/////MM//MM/MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMM/////MM/MM/M/MMM/mn=======nmMMMM/M/MM/////MMM///MMM/MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMM////MM/MMMMMMmn-=====nMMMMMMMMMMn=====nmMMMMMM///MMM//MMM////M/MMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMM///M/MMMMmm-======nMMMMm:::::::::::NMMMn-=======nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMM//MMMMMMm-====nMMMN::::::..............::::::MMMMn-======nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMM///MMMM-===nMMN:::::::....////XXXooo...........::::::::NMMn-====nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMM-==MMn:::...........////XX??-||-oo................:::::::::NMM-===MMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMM-===MNn:..............///XXXX??------oo.......................::::MMM==MMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMM==:.................iiii'''ii??----oooo...................::::MMM-===MMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMM==:...............iii'''''iiiii////oooo................:::MMMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMM==:::............iii''''''iii///oooo..............:::::MMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMM==::::.........iii'''''ooo//ooooo.........::::::MMMM-==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMM==::::::.....iioo'''''//ooooo.....::::::MMMM-==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMM==:::::::..ioooooooooo:::::::::MMMMMM==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMM  MMMMMMMMM  MM  MM      MM  MMMM  MMMM  MM.......MMM.......MMMMM...MMMMM.........MMMM......MMM\n")
  cat("MMMM  MMMMMMM  MM  MM  MMMMMM  MMM    MMM  MM..MMMMMMMM..MMMMM..MMM..M..MMMM..MMMMMM..MM..MMMMMMMM\n")
  cat("MMMMM  MMMMM  MM  MM  MMMMMM  MM  MM  MM  MM........MM..MMMMMMMMMM..MM..MMM..MMMMMM..MM..MMMMMMMMM\n")
  cat("MMMMMM  MMM  MM  MM      MM  M  MMMM  M  MMMMMMMMM..MM..MMMMMMMMM.......MMM.........MM.......MMMMM\n")
  cat("MMMMMMM  M  MM  MM  MMMMMM   MMMMMMM   MMM..MMMM...MM...MMMM..MM..MMMM..MMM..MMMMMMMM..MMMMMMMMMMM\n")
  cat("MMMMMMMM   MM  MM      MM  MMMMMMMMM  MMM.........MMM........MM..MMMMM..MM..MMMMMMMM.......MMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  cat("MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM\n")
  invisible()
}

.onUnload <- function(libpath)
{
  library.dynam.unload("viewscape", libpath)
}

#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM/MMM/MMM/M///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMM/M////MM/M/MM//////MM//MM///MM///MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMM/M////MM//MM/MM/MMMM//MMM///MM///MM/////MM//MM/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMM/////MM/MM/M/MMM/mn=======nmMMMM/M/MM/////MMM///MMM/MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMM////MM/MMMMMMmn-=====nMMMMMMMMMMn=====nmMMMMMM///MMM//MMM////M/MMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMM///M/MMMMmm-======nMMMMm:::::::::::NMMMn-=======nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMM//MMMMMMm-====nMMMN::::::..............::::::MMMMn-======nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MM///MMMM-===nMMN:::::::....////XXXooo...........::::::::NMMn-====nmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMM-==MMn:::...........////XX??-||-oo................:::::::::NMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMM
#MM-===MNn:..............///XXXX??------oo.......................::::MMM==MMMMMMMMMMMMMMMMMMMMMMMMMM
#MMM==:.................iiii'''ii??----oooo...................::::MMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMM==:...............iii'''''iiiii////oooo................:::MMMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMM==:::............iii''''''iii///oooo..............:::::MMM-===MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMM==::::.........iii'''''ooo//ooooo.........::::::MMMM-==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMM==::::::.....iioo'''''//ooooo.....::::::MMMM-==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMM==:::::::..ioooooooooo:::::::::MMMMMM==MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMmmmmmmmmmmMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MM..MMMMMMMMM..MM..MM......MM..MMMM..MMMM..MM.......MMM.......MMMMM...MMMMM.........MMMM......MMMMM
#MMM..MMMMMMM..MM..MM..MMMMMM..MM..M..MMM..MM..MMMMMMMM..MMMMM..MMM..M..MMMM..MMMMMM..MM..MMMMMMMMMM
#MMMM..MMMMM..MM..MM..MMMMMM..MM..MM..MM..MM........MM..MMMMMMMMMM..MM..MMM..MMMMMM..MM..MMMMMMMMMMM
#MMMMM..MMM..MM..MM......MM..M..MMMM..M..MMMMMMMMM..MM..MMMMMMMMM.......MMM.........MM.......MMMMMMM
#MMMMMM..M..MM..MM..MMMMMM...MMMMMMM...MMM..MMMM...MM...MMMM..MM..MMMM..MMM..MMMMMMMM..MMMMMMMMMMMMM
#MMMMMMM...MM..MM......MM..MMMMMMMMM..MMM.........MMM........MM..MMMMM..MM..MMMMMMMM.......MMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM
#MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM

